[project]
name = "pyspark-sample-project"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pyspark>=4.1.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
